name: CI

on:
    push: 
        branches: [main]

permissions: 
    contents: read
    packages: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Check Python syntax
              run: python -m py_compile main.py

            - name: Validate data
              run: python validate_data.py  

            - name: Build Docker image
              run: docker build -t fastapi-demo .
            
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Tag Docker image
              run: docker tag fastapi-demo ghcr.io/vicgrey/fastapi-demo:1.0

            - name: Push Docker image
              run: docker push ghcr.io/vicgrey/fastapi-demo:1.0
